/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.anggotahimasifcontrol;
import java.awt.event.KeyListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Muhammad Fahmy
 */
public class anggotahimasifview extends javax.swing.JFrame {

    /**
     * Creates new form datamahasiswaview
     */
    anggotahimasifcontrol dmc = new anggotahimasifcontrol(this);

    public anggotahimasifview() {
        initComponents();
        dmc.select();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        lagama = new javax.swing.JLabel();
        langkatan = new javax.swing.JLabel();
        cbAgama = new javax.swing.JComboBox<>();
        cbAngkatan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMahasiswa = new javax.swing.JTable();
        tNIM = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        tTanggalLahir = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        tAlamat = new javax.swing.JTextArea();
        tnomorHP = new javax.swing.JTextField();
        cbJabatan = new javax.swing.JComboBox<>();
        btnKembali = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        lalamat = new javax.swing.JLabel();

        jMenuItem1.setText("Hapus");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Refresh");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        lagama.setText("Agama");

        langkatan.setText("Angkatan");

        cbAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katolik", "Hindu", "Budha", "Konghucu" }));

        cbAngkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Intention", "Sensation", "Selection", "Infinity" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        tblMahasiswa.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tblMahasiswa.setForeground(new java.awt.Color(153, 153, 153));
        tblMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Tanggal Lahir", "Alamat", "Agama", "Nomor HP", "Angkatan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMahasiswa.setGridColor(new java.awt.Color(255, 255, 255));
        tblMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMahasiswaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblMahasiswaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblMahasiswa);
        if (tblMahasiswa.getColumnModel().getColumnCount() > 0) {
            tblMahasiswa.getColumnModel().getColumn(0).setResizable(false);
            tblMahasiswa.getColumnModel().getColumn(1).setResizable(false);
            tblMahasiswa.getColumnModel().getColumn(2).setResizable(false);
            tblMahasiswa.getColumnModel().getColumn(3).setResizable(false);
            tblMahasiswa.getColumnModel().getColumn(4).setResizable(false);
            tblMahasiswa.getColumnModel().getColumn(5).setResizable(false);
            tblMahasiswa.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 1160, 170));

        tNIM.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tNIM.setForeground(new java.awt.Color(153, 153, 153));
        tNIM.setBorder(null);
        tNIM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tNIMKeyReleased(evt);
            }
        });
        getContentPane().add(tNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 234, 40));

        tNama.setEditable(false);
        tNama.setBackground(new java.awt.Color(255, 255, 255));
        tNama.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tNama.setForeground(new java.awt.Color(153, 153, 153));
        tNama.setBorder(null);
        getContentPane().add(tNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 234, 40));

        tTanggalLahir.setEditable(false);
        tTanggalLahir.setBackground(new java.awt.Color(255, 255, 255));
        tTanggalLahir.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tTanggalLahir.setForeground(new java.awt.Color(153, 153, 153));
        tTanggalLahir.setBorder(null);
        getContentPane().add(tTanggalLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 387, 180, 30));

        btnSimpan.setBorder(null);
        btnSimpan.setBorderPainted(false);
        btnSimpan.setContentAreaFilled(false);
        btnSimpan.setEnabled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, 100, 50));

        btnUpdate.setBorder(null);
        btnUpdate.setBorderPainted(false);
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 380, 90, 50));

        btnDelete.setBorder(null);
        btnDelete.setBorderPainted(false);
        btnDelete.setContentAreaFilled(false);
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 380, 90, 50));

        tAlamat.setEditable(false);
        tAlamat.setColumns(20);
        tAlamat.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tAlamat.setForeground(new java.awt.Color(153, 153, 153));
        tAlamat.setRows(5);
        tAlamat.setBorder(null);
        getContentPane().add(tAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 260, 250, 90));

        tnomorHP.setEditable(false);
        tnomorHP.setBackground(new java.awt.Color(255, 255, 255));
        tnomorHP.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tnomorHP.setForeground(new java.awt.Color(153, 153, 153));
        tnomorHP.setBorder(null);
        getContentPane().add(tnomorHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 190, 30));

        cbJabatan.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        cbJabatan.setForeground(new java.awt.Color(153, 153, 153));
        cbJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ketua Umum", "Sekretaris", "Bendahara", "Kadiv PSDM", "Kadiv LITBANG", "Kadiv MEDIATEK", "Kadiv HUMAS", "Kasubdiv KADERISASI", "Kasubdiv IM", "Anggota LITBANG", "Anggota HUMAS", "Anggota MEDIATEK", "Anggota KADERISASI", "Anggota IM" }));
        cbJabatan.setBorder(null);
        getContentPane().add(cbJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 200, 30));

        btnKembali.setBorder(null);
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 180, 100, 40));

        btnBatal.setBorder(null);
        btnBatal.setBorderPainted(false);
        btnBatal.setContentAreaFilled(false);
        btnBatal.setEnabled(false);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 380, 100, 50));

        lalamat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lalamat.setForeground(new java.awt.Color(153, 153, 153));
        lalamat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/himasif.png"))); // NOI18N
        getContentPane().add(lalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        dmc.insert();
        dmc.select();
        dmc.cleartext();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        dmc.update();
        dmc.select();
        dmc.cleartext();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMahasiswaMouseClicked
        // TODO add your handling code here:
        dmc.row();
    }//GEN-LAST:event_tblMahasiswaMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dmc.delete();
        dmc.select();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:;
        dmc.select();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void tblMahasiswaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMahasiswaMouseReleased
        // TODO add your handling code here:
        if (evt.isPopupTrigger()) {
            jPopupMenu1.show(tblMahasiswa, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblMahasiswaMouseReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        dmc.delete();
        dmc.select();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here
        dmc.back();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void tNIMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNIMKeyReleased
        // TODO add your handling code here:
        dmc.cari();
    }//GEN-LAST:event_tNIMKeyReleased

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        dmc.batal();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anggotahimasifview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anggotahimasifview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anggotahimasifview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anggotahimasifview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anggotahimasifview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbAgama;
    private javax.swing.JComboBox<String> cbAngkatan;
    private javax.swing.JComboBox<String> cbJabatan;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lagama;
    private javax.swing.JLabel lalamat;
    private javax.swing.JLabel langkatan;
    private javax.swing.JTextArea tAlamat;
    private javax.swing.JTextField tNIM;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tTanggalLahir;
    private javax.swing.JTable tblMahasiswa;
    private javax.swing.JTextField tnomorHP;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getCbAgama() {
        return cbAgama;
    }

    public JComboBox<String> getCbAngkatan() {
        return cbAngkatan;
    }

    public JComboBox<String> getCbJabatan() {
        return cbJabatan;
    }

    public JTextArea gettAlamat() {
        return tAlamat;
    }

    public JTextField gettNIM() {
        return tNIM;
    }
    
    public String getNIM() {
        return tNIM.getText();
    }

    public JTextField gettNama() {
        return tNama;
    }

    public JTextField gettTanggalLahir() {
        return tTanggalLahir;

    }

    public JTextField getTnomorHP() {
        return tnomorHP;
    }

    public JTable getTblMahasiswa() {
        return tblMahasiswa;
    }

    public void setCbAgama(JComboBox<String> cbAgama) {
        this.cbAgama = cbAgama;
    }

    public void setCbAngkatan(JComboBox<String> cbAngkatan) {
        this.cbAngkatan = cbAngkatan;
    }

    public void settAlamat(JTextArea tAlamat) {
        this.tAlamat = tAlamat;
    }

    public void setAlamat(String tAlamat) {
        this.tAlamat.setText(tAlamat);
    }
    
    public void settNIM(JTextField tNIM) {
        this.tNIM = tNIM;
    }

    public void settNama(JTextField tNama) {
        this.tNama = tNama;
    }
    
    public void setNama(String Nama) {
        this.tNama.setText(Nama);
    }

    public void settTanggalLahir(JTextField tTanggalLahir) {
        this.tTanggalLahir = tTanggalLahir;
    }

    public void setTanggal(String tTanggalLahir) {
        this.tTanggalLahir.setText(tTanggalLahir);
    }
    
    public void setTblMahasiswa(JTable tblMahasiswa) {
        this.tblMahasiswa = tblMahasiswa;
    }

    public void setTnomorHP(JTextField tnomorHP) {
        this.tnomorHP = tnomorHP;
    }

    public void setnomorHP(String tnomorHP) {
        this.tnomorHP.setText(tnomorHP);
    }
    
    public void setCbJabatan(JComboBox<String> cbJabatan) {
        this.cbJabatan = cbJabatan;
    }
    
    public void keyNIM(KeyListener ls){
        this.tNIM.addKeyListener(ls);
    }

    public JButton getBtnSimpan() {
        return btnSimpan;
    }

    public void setBtnSimpan(boolean btnSimpan) {
        this.btnSimpan.setEnabled(btnSimpan);
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public void setBtnDelete(JButton btnDelete) {
        this.btnDelete = btnDelete;
    }

    public JButton getBtnUpdate() {
        return btnUpdate;
    }

    public void setBtnUpdate(JButton btnUpdate) {
        this.btnUpdate = btnUpdate;
    }

    public JButton getBtnBatal() {
        return btnBatal;
    }

    public void setBtnBatal(JButton btnBatal) {
        this.btnBatal = btnBatal;
    }

    
    
}
