/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import control.datamahasiswacontrol;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Muhammad Fahmy
 */
public class datamahasiswaview extends javax.swing.JFrame {

    /**
     * Creates new form datamahasiswaview
     */
    datamahasiswacontrol dmc = new datamahasiswacontrol(this);

    public datamahasiswaview() {
        initComponents();
        dmc.select();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        tTanggalLahir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMahasiswa = new javax.swing.JTable();
        tNIM = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cbAgama = new javax.swing.JComboBox<>();
        cbAngkatan = new javax.swing.JComboBox<>();
        tnomorHP = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAlamat = new javax.swing.JTextArea();
        tanggal = new com.toedter.calendar.JDateChooser();
        lalamat = new javax.swing.JLabel();

        jMenuItem1.setText("Hapus");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Refresh");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        tTanggalLahir.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tTanggalLahir.setForeground(new java.awt.Color(153, 153, 153));
        tTanggalLahir.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        tblMahasiswa.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tblMahasiswa.setForeground(new java.awt.Color(153, 153, 153));
        tblMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMahasiswa.setGridColor(new java.awt.Color(255, 255, 255));
        tblMahasiswa.setOpaque(false);
        tblMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMahasiswaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblMahasiswaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblMahasiswa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 1140, 170));

        tNIM.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tNIM.setForeground(new java.awt.Color(153, 153, 153));
        tNIM.setBorder(null);
        tNIM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tNIMKeyReleased(evt);
            }
        });
        getContentPane().add(tNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 234, 30));

        tNama.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tNama.setForeground(new java.awt.Color(153, 153, 153));
        tNama.setBorder(null);
        getContentPane().add(tNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 234, 40));

        btnSimpan.setBackground(new java.awt.Color(125, 217, 213));
        btnSimpan.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.setBorder(null);
        btnSimpan.setBorderPainted(false);
        btnSimpan.setContentAreaFilled(false);
        btnSimpan.setEnabled(false);
        btnSimpan.setOpaque(true);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 390, 80, 40));

        btnUpdate.setBackground(new java.awt.Color(125, 217, 213));
        btnUpdate.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("PERBARUI");
        btnUpdate.setBorder(null);
        btnUpdate.setBorderPainted(false);
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.setOpaque(true);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 390, 90, 40));

        btnDelete.setBackground(new java.awt.Color(125, 217, 213));
        btnDelete.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("HAPUS");
        btnDelete.setBorder(null);
        btnDelete.setBorderPainted(false);
        btnDelete.setContentAreaFilled(false);
        btnDelete.setOpaque(true);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 390, 90, 40));

        cbAgama.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        cbAgama.setForeground(new java.awt.Color(153, 153, 153));
        cbAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katolik", "Hindu", "Budha", "Konghucu" }));
        cbAgama.setBorder(null);
        cbAgama.setOpaque(false);
        getContentPane().add(cbAgama, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 210, 30));

        cbAngkatan.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        cbAngkatan.setForeground(new java.awt.Color(153, 153, 153));
        cbAngkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2013", "2014", "2015", "2016" }));
        cbAngkatan.setBorder(null);
        cbAngkatan.setOpaque(false);
        cbAngkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAngkatanActionPerformed(evt);
            }
        });
        getContentPane().add(cbAngkatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 210, 30));

        tnomorHP.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tnomorHP.setForeground(new java.awt.Color(153, 153, 153));
        tnomorHP.setBorder(null);
        getContentPane().add(tnomorHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 210, 30));

        btnKembali.setBackground(new java.awt.Color(241, 119, 120));
        btnKembali.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.setToolTipText("");
        btnKembali.setBorder(null);
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.setOpaque(true);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 190, 80, 40));

        btnBatal.setBackground(new java.awt.Color(241, 119, 120));
        btnBatal.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("BATAL");
        btnBatal.setBorder(null);
        btnBatal.setBorderPainted(false);
        btnBatal.setContentAreaFilled(false);
        btnBatal.setEnabled(false);
        btnBatal.setOpaque(true);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 390, 90, 40));

        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(153, 153, 153));

        tAlamat.setColumns(20);
        tAlamat.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tAlamat.setForeground(new java.awt.Color(153, 153, 153));
        tAlamat.setRows(5);
        jScrollPane2.setViewportView(tAlamat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 260, 240, 90));
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 170, 30));

        lalamat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lalamat.setForeground(new java.awt.Color(204, 204, 204));
        lalamat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/data mahasiswa.png"))); // NOI18N
        getContentPane().add(lalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        dmc.insert();
        dmc.select();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        dmc.update();
        dmc.select();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMahasiswaMouseClicked
        // TODO add your handling code here:
        dmc.row();
    }//GEN-LAST:event_tblMahasiswaMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dmc.delete();
        dmc.select();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:;
        dmc.select();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void tblMahasiswaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMahasiswaMouseReleased
        // TODO add your handling code here:
        if (evt.isPopupTrigger()) {
            jPopupMenu1.show(tblMahasiswa, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblMahasiswaMouseReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        dmc.delete();
        dmc.select();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        dmc.back();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        dmc.batal();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tNIMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNIMKeyReleased
        // TODO add your handling code here:
        dmc.check();
    }//GEN-LAST:event_tNIMKeyReleased

    private void cbAngkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAngkatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAngkatanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datamahasiswaview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datamahasiswaview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datamahasiswaview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datamahasiswaview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datamahasiswaview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbAgama;
    private javax.swing.JComboBox<String> cbAngkatan;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lalamat;
    private javax.swing.JTextArea tAlamat;
    private javax.swing.JTextField tNIM;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tTanggalLahir;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTable tblMahasiswa;
    private javax.swing.JTextField tnomorHP;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getCbAgama() {
        return cbAgama;
    }

    public JComboBox<String> getCbAngkatan() {
        return cbAngkatan;
    }

    public JTextArea gettAlamat() {
        return tAlamat;
    }

    public JTextField gettNIM() {
        return tNIM;
    }

    public JTextField gettNama() {
        return tNama;
    }

    public JTextField gettTanggalLahir() {
        return tTanggalLahir;
       
    }

    public JTextField getTnomorHP() {
        return tnomorHP;
    }

    public JTable getTblMahasiswa() {
        return tblMahasiswa;
    }

    public void setCbAgama(JComboBox<String> cbAgama) {
        this.cbAgama = cbAgama;
    }

    public void setCbAngkatan(JComboBox<String> cbAngkatan) {
        this.cbAngkatan = cbAngkatan;
    }

    public void settAlamat(JTextArea tAlamat) {
        this.tAlamat = tAlamat;
    }

    public void settNIM(JTextField tNIM) {
        this.tNIM = tNIM;
    }

    public void settNama(JTextField tNama) {
        this.tNama = tNama;
    }

    public void settTanggalLahir(JTextField tTanggalLahir) {
        this.tTanggalLahir = tTanggalLahir;
    }

    public void setTblMahasiswa(JTable tblMahasiswa) {
        this.tblMahasiswa = tblMahasiswa;
    }

    public void setTnomorHP(JTextField tnomorHP) {
        this.tnomorHP = tnomorHP;
    }

    public JButton getBtnBatal() {
        return btnBatal;
    }

    public void setBtnBatal(JButton btnBatal) {
        this.btnBatal = btnBatal;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public void setBtnDelete(JButton btnDelete) {
        this.btnDelete = btnDelete;
    }

    public JButton getBtnSimpan() {
        return btnSimpan;
    }

    public void setBtnSimpan(JButton btnSimpan) {
        this.btnSimpan = btnSimpan;
    }

    public JButton getBtnUpdate() {
        return btnUpdate;
    }

    public void setBtnUpdate(JButton btnUpdate) {
        this.btnUpdate = btnUpdate;
    }

    public JDateChooser getTanggal() {
        return tanggal;
    }

    public void setTanggal(JDateChooser tanggal) {
        this.tanggal = tanggal;
    }

}
