/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.formpenilaiancontrol;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Muhammad Fahmy
 */
public class formpenilaianview extends javax.swing.JFrame {

    /**
     * Creates new form formPenilaian
     */
    formpenilaiancontrol dmc = new formpenilaiancontrol(this);

    public formpenilaianview() {
        initComponents();
        dmc.select();
                this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSelesai = new javax.swing.JButton();
        tIdPendaftar = new javax.swing.JTextField();
        tPengalaman = new javax.swing.JTextField();
        tEtika = new javax.swing.JTextField();
        tPenampilan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNilai = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        tNIM = new javax.swing.JTextField();
        tnama = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        lPenampilan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSelesai.setBorder(null);
        btnSelesai.setBorderPainted(false);
        btnSelesai.setContentAreaFilled(false);
        btnSelesai.setEnabled(false);
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 400, 100, 40));

        tIdPendaftar.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tIdPendaftar.setForeground(new java.awt.Color(153, 153, 153));
        tIdPendaftar.setBorder(null);
        tIdPendaftar.setOpaque(false);
        tIdPendaftar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tIdPendaftarKeyReleased(evt);
            }
        });
        getContentPane().add(tIdPendaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 260, 190, 30));

        tPengalaman.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tPengalaman.setForeground(new java.awt.Color(153, 153, 153));
        tPengalaman.setBorder(null);
        tPengalaman.setOpaque(false);
        getContentPane().add(tPengalaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 150, 30));

        tEtika.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tEtika.setForeground(new java.awt.Color(153, 153, 153));
        tEtika.setBorder(null);
        tEtika.setOpaque(false);
        getContentPane().add(tEtika, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 150, 30));

        tPenampilan.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tPenampilan.setForeground(new java.awt.Color(153, 153, 153));
        tPenampilan.setBorder(null);
        tPenampilan.setOpaque(false);
        getContentPane().add(tPenampilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 150, 40));

        jScrollPane1.setBorder(null);

        tableNilai.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tableNilai.setForeground(new java.awt.Color(153, 153, 153));
        tableNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableNilai.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tableNilai);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 518, 1130, 170));

        btnKembali.setBorder(null);
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 180, 114, 50));

        tNIM.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tNIM.setForeground(new java.awt.Color(153, 153, 153));
        tNIM.setBorder(null);
        tNIM.setEnabled(false);
        tNIM.setOpaque(false);
        getContentPane().add(tNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 190, 30));

        tnama.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tnama.setForeground(new java.awt.Color(153, 153, 153));
        tnama.setBorder(null);
        tnama.setEnabled(false);
        tnama.setOpaque(false);
        getContentPane().add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 190, 30));

        btnBatal.setBorder(null);
        btnBatal.setBorderPainted(false);
        btnBatal.setContentAreaFilled(false);
        btnBatal.setEnabled(false);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 390, 100, 60));

        lPenampilan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lPenampilan.setForeground(new java.awt.Color(153, 153, 153));
        lPenampilan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/penilaian.png"))); // NOI18N
        getContentPane().add(lPenampilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        dmc.insert();
        dmc.select();
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void tIdPendaftarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tIdPendaftarKeyReleased
        // TODO add your handling code here:
        dmc.cari();
    }//GEN-LAST:event_tIdPendaftarKeyReleased

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        dmc.back();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        dmc.batal();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formpenilaianview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formpenilaianview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formpenilaianview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formpenilaianview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formpenilaianview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lPenampilan;
    private javax.swing.JTextField tEtika;
    private javax.swing.JTextField tIdPendaftar;
    private javax.swing.JTextField tNIM;
    private javax.swing.JTextField tPenampilan;
    private javax.swing.JTextField tPengalaman;
    private javax.swing.JTable tableNilai;
    private javax.swing.JTextField tnama;
    // End of variables declaration//GEN-END:variables

    public JTextField gettEtika() {
        return tEtika;
    }

    public JTextField gettIdPendaftar() {
        return tIdPendaftar;
    }

    public JTextField gettPenampilan() {
        return tPenampilan;
    }

    public JTextField gettPengalaman() {
        return tPengalaman;
    }

    public JTable getTableNilai() {
        return tableNilai;
    }

    public void settEtika(JTextField tEtika) {
        this.tEtika = tEtika;
    }

    public void settIdPendaftar(JTextField tIdPendaftar) {
        this.tIdPendaftar = tIdPendaftar;
    }

    public void settPenampilan(JTextField tPenampilan) {
        this.tPenampilan = tPenampilan;
    }

    public void settPengalaman(JTextField tPengalaman) {
        this.tPengalaman = tPengalaman;
    }

    public void setTableNilai(JTable tableNilai) {
        this.tableNilai = tableNilai;
    }

    public JTextField gettNIM() {
        return tNIM;
    }

    public void settNIM(JTextField tNIM) {
        this.tNIM = tNIM;
    }

    public JTextField getTnama() {
        return tnama;
    }

    public void setTnama(JTextField tnama) {
        this.tnama = tnama;
    }

    public JButton getBtnBatal() {
        return btnBatal;
    }

    public void setBtnBatal(JButton btnBatal) {
        this.btnBatal = btnBatal;
    }

    public JButton getBtnSelesai() {
        return btnSelesai;
    }

    public void setBtnSelesai(JButton btnSelesai) {
        this.btnSelesai = btnSelesai;
    }
    
    

}
